// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuDkh1TnB1R8stSfg1Kxz1izqPzG5pmM',
    appId: '1:627073917542:web:c7a2a9d22b435cd9b903a7',
    messagingSenderId: '627073917542',
    projectId: 'trav-280208',
    authDomain: 'trav-280208.firebaseapp.com',
    storageBucket: 'trav-280208.firebasestorage.app',
    measurementId: 'G-X28XXCG7KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7dlbYlpcEzdgnE367Kcg6kvVWfW7TUjk',
    appId: '1:627073917542:android:b59d2b5125c1bdd4b903a7',
    messagingSenderId: '627073917542',
    projectId: 'trav-280208',
    storageBucket: 'trav-280208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVTSXayeEbyeaE-SsIFsTOfY3LyVThp4',
    appId: '1:627073917542:ios:584f02184a84f2c9b903a7',
    messagingSenderId: '627073917542',
    projectId: 'trav-280208',
    storageBucket: 'trav-280208.firebasestorage.app',
    iosBundleId: 'com.example.temphumidityjehu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVTSXayeEbyeaE-SsIFsTOfY3LyVThp4',
    appId: '1:627073917542:ios:584f02184a84f2c9b903a7',
    messagingSenderId: '627073917542',
    projectId: 'trav-280208',
    storageBucket: 'trav-280208.firebasestorage.app',
    iosBundleId: 'com.example.temphumidityjehu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSfsAS3SUc4p9RE0TCf2CHdp38jdBe07o',
    appId: '1:627073917542:web:150349010a0cc71bb903a7',
    messagingSenderId: '627073917542',
    projectId: 'trav-280208',
    authDomain: 'trav-280208.firebaseapp.com',
    storageBucket: 'trav-280208.firebasestorage.app',
    measurementId: 'G-D03KJ2FQ00',
  );

}